#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#      defer-datasource-initialization: true
#      hibernate:
#        ddl-auto: create


spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS logistics
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: logistics
    generate-ddl: true
